--************ NETTOYAGE TABLE IMMATRICULATION ************--


--SUPPRESSION DES DOUBLONS

delete FROM ma_table 
where exists (
SELECT   COUNT(*) AS nbr_doublon, IMMATRICULATION
FROM     IMMATRICULATION
GROUP BY IMMATRICULATION
HAVING   COUNT(*) > 1;

--SUPPRESSION DES IMMATRICULATIONS FAUSSES

delete * from IMMATRICULATION where length(IMMATRICULATION) < 10;

--SUPPRESSION PUISSANCES INVALIDES

delete * from IMMATRICULATION 
WHERE PUISSANCE NOT BETWEEN '507' AND '55';

--SUPPRESSION DES NBPLACES INVALIDES

delete * from IMMATRICULATION 
WHERE NBPLACES NOT BETWEEN '5' AND '7';

--SUPPRESSION DES NBPORTES INVALIDES

delete * from IMMATRICULATION 
WHERE NBPORTES NOT BETWEEN '3' AND '5';

--VERIFICATION DE LA VARIABLE OCCASION

SELECT count(occasion) 
FROM IMMATRICULATION;







