--************ NETTOYAGE TABLE IMMATRICULATION ************--


--SUPPRESSION DES DOUBLONS


delete FROM ma_table 
where exists (
SELECT   COUNT(*) AS nbr_doublon, IMMATRICULATION
FROM     IMMATRICULATION
GROUP BY IMMATRICULATION
HAVING   COUNT(*) > 1;

--SUPPRESSION DES IMMATRICULATIONS FAUSSES

delete * from IMMATRICULATION where length(IMMATRICULATION) < 10;


--SUPPRESSION PUISSANCES INVALIDES

delete * from IMMATRICULATION 
WHERE PUISSANCE NOT BETWEEN '507' AND '55';

--SUPPRESSION DES NBPLACES INVALIDES

delete * from IMMATRICULATION 
WHERE NBPLACES NOT BETWEEN '5' AND '7';

--SUPPRESSION DES NBPORTES INVALIDES

delete * from IMMATRICULATION 
WHERE NBPORTES NOT BETWEEN '3' AND '5';

--VERIFICATION DE LA VARIABLE OCCASION

SELECT count(occasion) 
FROM IMMATRICULATION;



--************  NETTOYAGE TABLE CLIENT ************--

-- NETTOYAGE COLONNE SEXE

-- Les 'féminin' et 'Masculin' changent pour F et M
UPDATE CLIENT
SET sexe = 'F'
WHERE sexe = 'Féminin';

UPDATE CLIENT
SET sexe = 'M'
WHERE sexe = 'Masculin';

-- Suppression des données non conformes
DELETE * FROM CLIENT
WHERE sexe != 'M' OR sexe != 'F';

-- NETTOYAGE COLONNE X2emeVoiture
-- Suppression des données non conformes
DELETE deuxiemeVoiture FROM CLIENT
WHERE deuxiemeVoiture != 'true' OR deuxiemeVoiture != 'false';


--NETTOYAGE COLONNE SITUATIONFAMILIALE
--Vérification des données

SELECT DISTINCT SITUATIONFAMILIALE
FROM CLIENT;

--Les 'Seule' et 'Seul' changent pour 'Célibataire'
UPDATE CLIENT
SET SITUATIONFAMILIALE = 'Célibataire'
WHERE SITUATIONFAMILIALE='Seule' OR 'Seul';

 
--Suppression des données non conformes
DELETE *
FROM CLIENT
WHERE SITUATIONFAMILIALE = 'Divorcée';


--NETTOYAGE COLONNE NBENFANTSACHARGE

--Suppression des données invalides
DELETE *
FROM CLIENT
WHERE NBENFANTSACHARGE NOT BETWEEN 0 AND 4;


-- ************ PAS DE NETTOYAGE TABLE MARKETING POUR GARDER DES DONNEES ************ --

